In [1]:
import h5py
import numpy as np
import matplotlib.pyplot as plt
import os

In [27]:
####### option ########

# show the structure of HDF5 file and shape of data
file_names = os.listdir('../data/')
print_counter_till_end = 0
for name in file_names:
    if name.find('h5')<0:
        continue
    print('<<<<<<<'+name+'<<<<<<<')
    print_counter_till_end +=1
    with h5py.File('../data/'+name) as f:
        for key in f:
            data_shape =np.array(f[key])
            print(key+' --- '+str(np.shape(f[key])))
            if print_counter_till_end == 1:
                print('  |-- number of attributes = ' + str(len(f[key].attrs.keys())))
            if print_counter_till_end == 2:
#                 pass
                print(np.array(f[key]))
            
    

<<<<<<<bedroom_04.h5<<<<<<<
graph --- (408, 4)
  |-- number of attributes = 0
location --- (408, 2)
  |-- number of attributes = 0
observation --- (408, 300, 400, 3)
  |-- number of attributes = 0
resnet_feature --- (408, 10, 2048)
  |-- number of attributes = 0
rotation --- (408,)
  |-- number of attributes = 0
shortest_path_distance --- (408, 408)
  |-- number of attributes = 0
<<<<<<<bathroom_02.h5<<<<<<<
graph --- (180, 4)
[[ 16   1   3  -1]
 [ -1   2   0  -1]
 [ -1   3   1  18]
 [ -1   0   2  -1]
 [ -1   5   7  -1]
 [  9   6   4  -1]
 [ -1   7   5  -1]
 [ -1   4   6  11]
 [ -1   9  11  -1]
 [ 13  10   8   5]
 [ -1  11   9  -1]
 [  7   8  10  15]
 [ 20  13  15  -1]
 [ -1  14  12   9]
 [ -1  15  13  22]
 [ 11  12  14  -1]
 [ 32  17  19   0]
 [ -1  18  16  -1]
 [  2  19  17  34]
 [ -1  16  18  -1]
 [ 40  21  23  12]
 [ 25  22  20  -1]
 [ 14  23  21  42]
 [ -1  20  22  27]
 [ 44  25  27  -1]
 [ 29  26  24  21]
 [ -1  27  25  46]
 [ 23  24  26  31]
 [ 48  29  31  -1]
 [ 33  30  28  25]

observation --- (180, 300, 400, 3)
[[[[187 180 164]
   [187 180 164]
   [187 180 164]
   ...
   [252 255 253]
   [249 255 251]
   [251 255 255]]

  [[187 180 164]
   [187 180 164]
   [187 180 164]
   ...
   [252 255 251]
   [249 255 251]
   [251 255 255]]

  [[187 180 164]
   [187 180 164]
   [187 180 164]
   ...
   [252 255 251]
   [250 255 251]
   [251 255 253]]

  ...

  [[ 80  67  48]
   [ 80  67  48]
   [ 80  67  48]
   ...
   [ 76  75  70]
   [ 78  77  72]
   [ 81  80  75]]

  [[ 80  67  48]
   [ 80  67  48]
   [ 80  67  48]
   ...
   [ 75  74  69]
   [ 78  77  72]
   [ 81  80  75]]

  [[ 80  67  48]
   [ 80  67  48]
   [ 80  67  48]
   ...
   [ 75  74  69]
   [ 78  77  72]
   [ 80  79  74]]]


 [[[196 194 181]
   [196 194 181]
   [195 193 180]
   ...
   [ 58  57  53]
   [ 58  57  53]
   [ 58  57  53]]

  [[195 193 180]
   [195 193 180]
   [195 193 180]
   ...
   [ 58  57  53]
   [ 58  57  53]
   [ 58  57  53]]

  [[194 192 179]
   [194 192 179]
   [194 192 179]
   ...
   [ 58  5

observation --- (468, 300, 400, 3)
resnet_feature --- (468, 10, 2048)
rotation --- (468,)
shortest_path_distance --- (468, 468)
<<<<<<<kitchen_02.h5<<<<<<<
graph --- (676, 4)
location --- (676, 2)
observation --- (676, 300, 400, 3)
resnet_feature --- (676, 10, 2048)
rotation --- (676,)
shortest_path_distance --- (676, 676)
